name: build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_REPOSITORY: omnidapps/odoo

jobs:
  build_and_publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # NOTE: Inflexible if there are multiple images, but this is fine for now.
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:master"
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:master
          labels: ${{ steps.meta.outputs.labels }}

